eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.33.72:8761/eureka/
server:
  port: 7073
spring:
  application:
    name: zuulsqweqeqweqweqe
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: SERVICE-RIBBON
    api-b:
      path: /api-b/**
      serviceId: SERVICE-RIBBON 
